version: '2'
services:

  dm:
    image: opv-dm
    ports:
      - "5005:5000"
      - "2121:2121"
      - "5050:5050"
  
  postgres:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: opv
      POSTGRES_PASSWORD: opv42
      POSTGRES_DB: opv
    ports:
      - "5432:5432"

  dbrest:
    image: opv-dbrest
    depends_on:
      - postgres
    environment:
      OPV_DBREST_USER: opv
      OPV_DBREST_PASSWORD: opv42
      OPV_DBREST_DB: opv
      OPV_DBREST_DB_ADDRESS: postgres
    ports:
      - "5000:5000"

  redis:
    image: redis

  celery:
    image: opv-celery
    depends_on:
      - redis
      - dbrest
      - dm

  flower:
    image: opv-flower
    depends_on:
      - redis
    ports:
      - "5555:5555"
